live_config_reload=true

[env]
WINIT_X11_SCALE_FACTOR="1.0"

[window]
decorations="transparent"
dynamic_padding=false
dynamic_title=true
opacity=0.8
padding.x=20
padding.y=15

[window.dimensions]
columns=92
lines=30

[shell]
program="/bin/bash"

[mouse]
hide_when_typing=true

[font]
builtin_box_drawing=true
size=11

[font.offset]
x=0
y=1

[selection]
save_to_clipboard=true

[scrolling]
history=3000

[[keyboard.bindings]]
action="ToggleFullscreen"
key="F11"

[[keyboard.bindings]]
action="Copy"
key="Copy"
mods="None"

[[keyboard.bindings]]
action="Paste"
key="Paste"
mods="None"

[[keyboard.bindings]]
action="Copy"
key="C"
mods="Control|Shift"

[[keyboard.bindings]]
action="Paste"
key="V"
mods="Control|Shift"

[[keyboard.bindings]]
action="PasteSelection"
key="Insert"
mods="Shift"

